name: git-config
version: '0.1.2'
synopsis: A simple parser for Git configuration files
description: |
  git-config is a simple 'megaparsec' parser for Git configuration files.

  It aims to provide the simplest API possible for parsing Git configuration
  files so that you can get to whatever it was you were doing.

  A sample of this library in use:

  > import qualified Data.Text.IO as TIO
  > import Text.GitConfig.Parser (parseConfig)
  >
  > main :: IO ()
  > main = do
  >   file <- TIO.readFile ".git/config"
  >   case parseConfig file of
  >     Right conf ->
  >       print conf
category: Library,Git
author: Fernando Freire
maintainer: Fernando Freire <dogonthehorizon@gmail.com>
copyright: 2018 Fernando Freire
license: BSD3
github: dogonthehorizon/git-config

extra-source-files:
  - README.md

dependencies:
  - base >=4.7 && <5
  - text
  - unordered-containers
default-extensions:
  - OverloadedStrings
ghc-options:
  - -Wall
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns


library:
  source-dirs: src
  dependencies:
    - megaparsec >= 7 && < 10
  exposed-modules:
    - Text.GitConfig.Parser

tests:
  git-config-test:
    build-tools: tasty-discover:tasty-discover ^>=4.2.1
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - git-config
      - megaparsec
      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-hedgehog
